// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkO8zW8xaHyIixQeQhqSHXoZFLjJ7F6UA',
    appId: '1:112606577122:web:bd3c134309dfaaf535f9bb',
    messagingSenderId: '112606577122',
    projectId: 'foodxpress-fbbbb',
    authDomain: 'foodxpress-fbbbb.firebaseapp.com',
    storageBucket: 'foodxpress-fbbbb.firebasestorage.app',
    measurementId: 'G-VDTRS2Y445',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzoNY6uL-nQbBbaDzNdHs2emfnPa5-i6k',
    appId: '1:112606577122:android:c83b70e4c570b64e35f9bb',
    messagingSenderId: '112606577122',
    projectId: 'foodxpress-fbbbb',
    storageBucket: 'foodxpress-fbbbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrcJfwnlU1TIu2jPAMGXFVaTOOGOB__Pk',
    appId: '1:112606577122:ios:3b390461c11ca39335f9bb',
    messagingSenderId: '112606577122',
    projectId: 'foodxpress-fbbbb',
    storageBucket: 'foodxpress-fbbbb.firebasestorage.app',
    iosBundleId: 'com.example.foodxpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrcJfwnlU1TIu2jPAMGXFVaTOOGOB__Pk',
    appId: '1:112606577122:ios:3b390461c11ca39335f9bb',
    messagingSenderId: '112606577122',
    projectId: 'foodxpress-fbbbb',
    storageBucket: 'foodxpress-fbbbb.firebasestorage.app',
    iosBundleId: 'com.example.foodxpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkO8zW8xaHyIixQeQhqSHXoZFLjJ7F6UA',
    appId: '1:112606577122:web:25ab3e52bb21e86735f9bb',
    messagingSenderId: '112606577122',
    projectId: 'foodxpress-fbbbb',
    authDomain: 'foodxpress-fbbbb.firebaseapp.com',
    storageBucket: 'foodxpress-fbbbb.firebasestorage.app',
    measurementId: 'G-YB4TBQX7XT',
  );

}